spring:
  datasource:
    url: jdbc:sqlserver://sasspasshost.database.windows.net:1433;database=dataprocessing;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: nhl_supervisor
    password: RjJKTTRrqiJpKH3
    jpa:
      database-platform: org.hibernate.dialect.SQLServerDialect
      hibernate:
        ddl-auto: update
      show-sql: true
      sql:
        init:
          mode: always